# Site settings
title: Octant
email:
author: Octant Authors
description: Validate your Kubernetes configuration
#url: https://octant.dev
logo: octant-logo.png
twitter:
  username: projectoctant
  card: summary
vm_logo: vm-logo.png
gh_repo: https://github.com/vmware-tanzu/octant
markdown: redcarpet
hero:
  background-color: med-blue
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title:
  cta_url: /docs
  cta_text: Documentation
  vm-link: http://vmware.github.io/

footer_social_links:
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/projectoctant
  Slack:
    fa_icon: fab fa-slack
    url: https://kubernetes.slack.com/app_redirect?channel=CM37M9FCG
  RSS:
    fa_icon: fa fa-rss
    url: /feed.xml
  GitHub:
    fa_icon: fab fa-github
    url: https://github.com/vmware-tanzu/octant

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: docs/master
    values:
      version: master
      gh: https://github.com/vmware-tanzu/octant/tree/master
      layout: "docs"

page_gen:
  - data: shortlinks
    template: redirect
    name: key
    dir: docs

collections:
  - contributors
  - casestudies

versioning: false
latest: master
versions:
- master

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)
  - jekyll-redirect-from
  - jekyll-seo-tag

# Include these subdirectories
include:
  - CONTRIBUTING.md
  - README.md

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - LICENSE
  - CNAME
  - Runbook.docx
  - '*.sh'

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
