# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
data:
  app.config: |
    {
      "app_Name": "example app",
      "users": [
        "user1",
        "user2"
      ]
    }
